replicaCount: 1

image:
  repository: mamutuberalles/helloapp # TODO change it to my-image
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}